repos:
  - repo: local
    hooks:
      - id: pylint
        name: pyling
        entry: pylint
        language: system
        types: [python]
        args: [
          "-rn", # Only display messages
          "-sn", # Do not display the column number (score)
          "--rcfile=.pylintrc", # Use the .pylintrc file
          "--load-plugins=pylint.extensions.docparams", # Load an extension
        ]
